<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.*" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.*" />
    <ProjectReference Include="..\FastDbExplorer.Application\FastDbExplorer.Application.csproj" />
  </ItemGroup>
</Project>
